---
version: "3"

services:
  pihole-api:
    image: bryanendres/pihole-api
    ports:
      - $HOST_PORT:$CONTAINER_PORT
    environment:
      - CONTAINER_PORT=$CONTAINER_PORT
      - HOST_IP=$HOST_IP
    restart: unless-stopped
    container_name: pihole-api
    volumes:
      - $DATA_DIR:/app
