/*
 * PiHole Management API
 *
 * A management webservice to be run locally on a PiHole instance
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"encoding/json"
)



type GravityIdDelete404Response struct {

	Id int32 `json:"id,omitempty"`

	Status string `json:"status,omitempty"`
}

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *GravityIdDelete404Response) UnmarshalJSON(data []byte) error {

	type Alias GravityIdDelete404Response // To avoid infinite recursion
    return json.Unmarshal(data, (*Alias)(m))
}

// AssertGravityIdDelete404ResponseRequired checks if the required fields are not zero-ed
func AssertGravityIdDelete404ResponseRequired(obj GravityIdDelete404Response) error {
	return nil
}

// AssertGravityIdDelete404ResponseConstraints checks if the values respects the defined constraints
func AssertGravityIdDelete404ResponseConstraints(obj GravityIdDelete404Response) error {
	return nil
}
