# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Go
      run: wget https://go.dev/dl/go1.20.6.linux-amd64.tar.gz && \ 
        rm -rf /usr/local/go && \
        tar -C /usr/local -xzf go1.20.6.linux-amd64.tar.gz && \
        export PATH=$PATH:/usr/local/go/bin && \
        go version

    - name: Test
      run: go test -v go/...

    - name: Get pihole-api
      run: go get github.com/bendres97/pihole-api

    - name: Build amd64
      run: go build -o pihole-api_linux_amd64 -v 

    - name: Build arm64
      run: go build -o pihole-api_linux_arm64 -v 

    - name: Build 386
      run: go build -o pihole-api_linux_386 -v 

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: pihole-api_linux_*
        tag: ${{ github.ref }}
        overwrite: true
